from __future__ import annotations

import pandas as pd
import streamlit as st
from sqlalchemy import create_engine

DB_PATH = "data/esg_simulation.db"


@st.cache_resource
def get_engine():
    return create_engine(f"sqlite:///{DB_PATH}", future=True)


def load_emissions_view() -> pd.DataFrame:
    query = """
    SELECT
        s.id AS supplier_id,
        s.industry,
        s.size,
        s.region,
        ROUND(s.esg_maturity, 3) AS esg_maturity,
        ROUND(t.true_emissions, 2) AS true_emissions,
        ROUND(r.reported_emissions, 2) AS reported_emissions,
        ROUND((r.reported_emissions - t.true_emissions), 2) AS emissions_delta
    FROM suppliers s
    JOIN true_esg_metrics t ON t.supplier_id = s.id
    JOIN reported_esg_metrics r ON r.supplier_id = s.id
    ORDER BY s.id DESC
    """
    with get_engine().connect() as conn:
        return pd.read_sql(query, conn)


def main() -> None:
    st.set_page_config(page_title="Synthetic ESG Monitor", layout="wide")
    st.title("Supplier ESG: True vs. Reported Emissions")
    st.caption("Synthetic training data generated by the ESG simulation pipeline")

    try:
        df = load_emissions_view()
    except Exception as exc:
        st.error(f"Unable to read database at {DB_PATH}: {exc}")
        st.info("Run: python -m src.run_pipeline --n-suppliers 200")
        return

    col1, col2, col3 = st.columns(3)
    col1.metric("Suppliers", int(df["supplier_id"].nunique()) if not df.empty else 0)
    col2.metric("Avg True Emissions", float(df["true_emissions"].mean()) if not df.empty else 0.0)
    col3.metric("Avg Reported Emissions", float(df["reported_emissions"].mean()) if not df.empty else 0.0)

    st.dataframe(df, use_container_width=True)


if __name__ == "__main__":
    main()
